### ISSUE TITLE
Introduce `gosec` for Static Application Security Testing (SAST)

### ISSUE THREAD

**Issue by JordanJordanov** [gardener/diki#331]
**What would you like to be added**:
Please, ensure that linting is enabled, a new release is created, and deployed.

You can use this [PR](https://github.com/gardener/gardener/pull/9959) from g/g for reference

**Why is this needed**:
Security & Compliance

**Comment by dimityrmirchev** [comment]
Easier to digest PR will be https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/248. You can use that as a reference
