### ISSUE TITLE
Support V1R11 of Kubernetes STIG

### ISSUE THREAD

**Issue by JordanJordanov** [gardener/diki#63]
**What would you like to be added**:
See differences with previous revision at https://cyber.trackr.live/stig/Kubernetes/1/11/1/10 and compile a list of implementation tasks.

**Why is this needed**:
Validate a cluster against the latest DISA Kubernetes STIGs rules.

### 0 added rules:
n/a

### 2 removed rules:

- [x] 242401 https://github.com/gardener/diki/pull/65
- [x] 242435 https://github.com/gardener/diki/pull/65

### 26 updated rules:

- [x] 242379 No changes required.
- [x] 242380 No changes required.
- [x] 242381 No changes required.
- [x] 242382 No changes required.
- [x] 242386 No changes required.
- [x] 242388 No changes required.
- [x] 242389 No changes required.
- [x] 242390 No changes required.
- [x] 242397 No changes required. See https://github.com/gardener/diki/issues/63#issuecomment-1838048942
- [x] 242400 No changes required.
- [x] 242402 No changes required.
- [x] 242403 No changes required.
- [x] 242418 No changes required.
- [x] 242421 No changes required.
- [x] 242426 No changes required.
- [x] 242429 No changes required.
- [x] 242430 No changes required.
- [x] 242431 No changes required.
- [x] 242438 No changes required.
- [x] 242447 No changes required.
- [x] 242448 No changes required.
- [x] 242460 No changes required.
- [x] 242462 No changes required.
- [x] 242466 No changes required.
- [x] 245543 No changes required.
- [x] 254800 No changes required.

**Comment by dimityrmirchev** [comment]
There are mostly rewording changes. The most notable differences are the removal of 242401 and 242435 rules.

**Comment by dimityrmirchev** [comment]
/reopen

Until we discuss if any changes are required to 242397.

**Comment by dimityrmirchev** [comment]
Let's not modify 242397 further since we already check all cluster nodes. In the gardener provider case control plane nodes exist in a different cluster which can be checked separately.
